# Generated by Django 3.0.6 on 2020-06-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('NewsLetterID', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(blank=True, max_length=70)),
            ],
        ),
    ]
