# Generated by Django 3.0.6 on 2020-06-15 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('CarID', models.AutoField(primary_key=True, serialize=False)),
                ('EngineType', models.TextField(blank=True)),
                ('PopulationType', models.TextField(blank=True)),
                ('Price', models.FloatField(blank=True, null=True)),
                ('FuelType', models.TextField(blank=True)),
                ('Doors', models.IntegerField(blank=True, null=True)),
                ('Capacity', models.IntegerField(blank=True, null=True)),
                ('GearCase', models.CharField(max_length=16)),
                ('Sitting_Place', models.IntegerField(blank=True, null=True)),
                ('FirstRegistrationDate', models.DateField(blank=True, null=True)),
                ('EnginePower', models.FloatField(blank=True, null=True)),
                ('other', models.CharField(max_length=16, null=True)),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('slug', models.SlugField(max_length=75)),
                ('number', models.CharField(max_length=16, unique=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('published', 'Published'), ('sold', 'Sold'), ('archived', 'Archived')], default='pending', max_length=15)),
                ('extra_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title second part')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('BrandID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('logo', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Car brand',
                'verbose_name_plural': 'Car brands',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('ModelID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Car model',
                'verbose_name_plural': 'Car models',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('ColorID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('PictureID', models.AutoField(primary_key=True, serialize=False)),
                ('URL', models.URLField()),
                ('Position', models.CharField(max_length=64)),
                ('Metadata', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddIndex(
            model_name='color',
            index=models.Index(fields=['name'], name='cars_color_name_95ff05_idx'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.CarBrand'),
        ),
        migrations.AddIndex(
            model_name='carbrand',
            index=models.Index(fields=['name'], name='cars_carbra_name_e5d8f6_idx'),
        ),
        migrations.AddField(
            model_name='car',
            name='ColorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Color'),
        ),
    ]
