# Generated by Django 3.0.6 on 2020-06-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=64)),
                ('FirstName', models.CharField(max_length=64)),
                ('LastName', models.CharField(max_length=64)),
                ('Email', models.EmailField(blank=True, max_length=70)),
                ('Phone', models.CharField(default='0-000-000-00', max_length=64)),
            ],
        ),
    ]
