# Generated by Django 3.0.6 on 2020-06-15 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('PropertyID', models.AutoField(primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=64)),
                ('Name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CarProperty',
            fields=[
                ('CarPropertyID', models.AutoField(primary_key=True, serialize=False)),
                ('CarID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car')),
                ('PropertyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
            ],
        ),
    ]
